#> gcloud app deploy app.yaml cron.yaml --no-promote --project testgoprivate -v testgoprivate-2024-10-09
runtime:     go122
app_engine_apis:  true

handlers:
- url: /static
  static_dir: static
- url: /html
  static_dir: html
- url: /res
  static_dir: res
- url: /update
  script: auto
  secure: always
  login: admin
- url: /.*
  script: auto
  secure: always
  login: optional